*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 16:43:21 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x16ce9d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x16ce9d0 pid: 20536 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 20536, cores: 1)
spawned uWSGI worker 2 (pid: 20539, cores: 1)
[pid: 20536|app: 0|req: 1/1] 222.209.181.22 () {42 vars in 1079 bytes} [Fri Feb 12 16:43:25 2016] GET / => generated 218404 bytes in 44 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20539|app: 0|req: 1/2] 222.209.181.22 () {44 vars in 1132 bytes} [Fri Feb 12 16:43:27 2016] GET /select/ => generated 1626 bytes in 35 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20536|app: 0|req: 2/3] 222.209.181.22 () {44 vars in 1161 bytes} [Fri Feb 12 16:43:28 2016] GET /select/template_1/ => generated 82701 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20539|app: 0|req: 2/4] 222.209.181.22 () {44 vars in 1182 bytes} [Fri Feb 12 16:43:31 2016] GET /select/template_1/edit/ => generated 23884 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/view/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./question_naire/views.py", line 47, in view
    s = Statics.objects.create(key='head', user=UserDefine.objects.get(username="Hang"))
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 401, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 700, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 728, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 812, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 851, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 1064, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: question_naire_statics
[pid: 20536|app: 0|req: 3/5] 222.209.181.22 () {50 vars in 1300 bytes} [Fri Feb 12 16:44:16 2016] POST /select/template_1/view/ => generated 19183 bytes in 84 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
[pid: 20539|app: 0|req: 3/6] 222.209.181.22 () {44 vars in 1171 bytes} [Fri Feb 12 16:44:16 2016] GET /select/success/ => generated 14374 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Not Found: /user_form_folders
[pid: 20539|app: 0|req: 4/7] 222.209.181.22 () {44 vars in 1100 bytes} [Fri Feb 12 16:44:17 2016] GET /user_form_folders => generated 3156 bytes in 8 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 20536|app: 0|req: 4/8] 222.209.181.22 () {44 vars in 1180 bytes} [Fri Feb 12 16:44:18 2016] GET /select/template_1/view/ => generated 64777 bytes in 6 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20539|app: 0|req: 5/9] 222.209.181.22 () {40 vars in 942 bytes} [Fri Feb 12 16:44:26 2016] GET /select/template_1/view/ => generated 64777 bytes in 7 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20536|app: 0|req: 5/10] 222.209.181.22 () {50 vars in 1175 bytes} [Fri Feb 12 16:44:37 2016] POST /select/template_1/analysis/ => generated 27 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
