*** Starting uWSGI 2.0.11.2 (64bit) on [Thu Feb  4 23:41:04 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib/Questionnaire
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x22cf9d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x22cf9d0 pid: 11566 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 11566, cores: 1)
spawned uWSGI worker 2 (pid: 11569, cores: 1)
[pid: 11566|app: 0|req: 1/1] 117.172.26.120 () {40 vars in 872 bytes} [Thu Feb  4 23:41:10 2016] GET / => generated 218404 bytes in 44 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 11569|app: 0|req: 1/2] 117.172.26.120 () {40 vars in 872 bytes} [Thu Feb  4 23:41:14 2016] GET / => generated 218404 bytes in 41 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 11566|app: 0|req: 2/3] 117.172.26.120 () {40 vars in 886 bytes} [Thu Feb  4 23:41:20 2016] GET /select/ => generated 1626 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 11566|app: 0|req: 3/4] 117.172.26.120 () {40 vars in 886 bytes} [Thu Feb  4 23:41:23 2016] GET /select/ => generated 1626 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/analysis/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./question_naire/views.py", line 56, in analysis
    ans = ans[2:len(ans)-3].split("],[")
TypeError: object of type 'NoneType' has no len()
[pid: 11569|app: 0|req: 2/5] 117.172.26.120 () {40 vars in 926 bytes} [Thu Feb  4 23:41:23 2016] GET /select/template_1/analysis/ => generated 56214 bytes in 88 msecs (HTTP/1.1 500) 2 headers in 92 bytes (1 switches on core 0)
[pid: 11566|app: 0|req: 4/6] 117.172.26.120 () {40 vars in 908 bytes} [Thu Feb  4 23:41:27 2016] GET /select/template_1/ => generated 82701 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 11569|app: 0|req: 3/7] 117.172.26.120 () {40 vars in 918 bytes} [Thu Feb  4 23:41:30 2016] GET /select/template_1/view/ => generated 68824 bytes in 8 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 11566|app: 0|req: 5/8] 117.172.26.120 () {40 vars in 918 bytes} [Thu Feb  4 23:41:31 2016] GET /select/template_1/view/ => generated 68824 bytes in 7 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 11569|app: 0|req: 4/9] 117.172.26.120 () {42 vars in 964 bytes} [Thu Feb  4 23:42:14 2016] GET /submit/welcome/ => generated 12519 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Not Found: /user_form_folders
[pid: 11569|app: 0|req: 5/10] 117.172.24.84 () {44 vars in 939 bytes} [Thu Feb  4 23:42:15 2016] GET /user_form_folders => generated 3026 bytes in 6 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 11566|app: 0|req: 6/11] 117.172.26.120 () {42 vars in 987 bytes} [Thu Feb  4 23:44:12 2016] GET /submit/welcome/ => generated 12519 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Not Found: /user_form_folders
[pid: 11566|app: 0|req: 7/12] 117.172.26.120 () {44 vars in 962 bytes} [Thu Feb  4 23:44:13 2016] GET /user_form_folders => generated 3026 bytes in 6 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
